### ISSUE TITLE
Prevent default undefined_1.js from opening every time

### ISSUE THREAD

**Issue by chivesz** [andrewbrg/codepad-chrome-app#30] opened 2019-03-10 08:31 UTC
Please? This is a great editor, but there is no reason for this to open EVERY time. I could understand first run, however closing it every time is getting old...

**Comment by newsametcalfe** [comment] 2019-08-30 05:00
May let us set a default file type to open, I mainly use .sql

**Comment by coder0107git** [comment] 2022-11-17 04:51
Duplicate of #15. @chivesz Please close this issue.

**Closed** 2022-11-17 05:14 UTC

**Comment by coder0107git** [comment] 2022-11-17 06:19
@chivesz  Thank you for closing this issue.
